pipelines:
  - name: onboard_talet_maven_pipeline
    configuration:
      environmentVariables:
        readOnly:
          mvnLocalRepo: onboard-repo-local
          artifactoryIp: 35.207.183.14:8082
          dockerVirtualRepo: onboard-docker-repo-virt
    steps:
      - name: mvn_build
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: -B -DskipTests clean install -ntp -s settings.xml
          configFileLocation: .
          configFileName: mvn-art-config
          autoPublishBuildInfo: true
          inputResources:
            - name: taletRepo
          outputResources:
            - name: taletBuildInfo
          integrations:
            - name: ob_artifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
            - ls ${res_taletRepo_resourcePath}
      - name: mvn_unit_test
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: test -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputSteps:
            - name: mvn_build
          inputResources:
            - name: taletRepo
          integrations:
            - name: ob_artifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: affinityGroup1
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: ${artifactoryIp}/${dockerVirtualRepo}/onboard-talet-maven
          dockerImageTag: ${run_number}
          inputSteps:
            - name: mvn_build
            - name: mvn_unit_test
          integrations:
            - name: ob_artifactory
          inputResources:
            - name: taletRepo
            - name: taletMavenFileSpec
          outputResources:
            - name: taletImage
        execution:
          onStart:
#            - jfrog rt dl ${mvnLocalRepo} --build=onboard_talet_maven_pipeline --flat=true # JFrog CLI - build name == pipeline name
#            - ls -ltra ${res_taletRepo_resourcePath}
            - cd ${res_taletMavenFileSpec_resourcePath}
            - ls -ltra target/
#            - mkdir target
#            - cp *.jar target/
            - mv -v target ${res_taletRepo_resourcePath}
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: affinityGroup1
          targetRepository: ${dockerVirtualRepo}
          inputSteps:
            - name: docker_build
          integrations:
            - name: ob_artifactory
          outputResources:
            - name: taletImage