resources:
  - name: taletRepo
    type: GitRepo
    configuration:
      gitProvider: github
      path: etingertal/onboard-talet-maven
pipelines:
  - name: onboard_talet_maven_pipeline
    steps:
      - name: mvn_build
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: -B -DskipTests clean package -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: taletRepo
          integrations:
            - name: ob_artifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
            - ls ${res_taletRepo_resourcePath}
      - name: mvn_unit_test
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: test -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: taletRepo
          integrations:
            - name: ob_artifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"