resources:
  - name: taletRepo
    type: GitRepo
    configuration:
      gitProvider: github
      path: etingertal/onboard-talet-maven
pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: mvn_build
          type: MvnBuild
          configuration:
            sourceLocation: .
            mvnCommand: clean install -ntp
            configFileLocation: .
            configFileName: mvn-art-config
            inputResources:
              - name: taletRepo
            integrations:
              - name: ob_artifactory
            runtime:
              type: image
              image:
                auto:
                  language: java
                  versions:
                    - "11"
          execution:
            onStart:
              - javac -version
              - mvn --version