# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and Artifactory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: JFrog CLI Config
      uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.artifactory_token_1 }}
    - name: JFrog CLI Ping
      run: |
        # Ping the server
        jfrog rt ping
#        jfrog rt config show
    - name: Set up JDK 111
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: jfrog rt mvn clean package -f pom.xml -DskipTests
    - name: Test with Maven
      run: jfrog rt mvn test -f pom.xml
    - name: Publish Build Info
      run: |
        jfrog rt bce $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
        jfrog rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER