# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# jfrog c == staging-emea

name: talet-maven-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: JFrog CLI Config
      uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.artifactory_token_1 }}
    - name: JFrog CLI Ping
      run: |
        # Ping the server
        jfrog rt ping
#        jfrog rt config show
    - name: Maven EnvVar Config
      run: |
        # M2_HOME
        echo "M2_HOME=/usr/share/apache-maven-3.6.3" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: jfrog rt mvn clean package -f pom.xml -DskipTests
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Test with Maven
      run: jfrog rt mvn test -f pom.xml
    - name: Publish Build Info
      run: |
        jfrog rt bce
        jfrog rt bp
    - name: Scan with XRay
      run: |
        jfrog rt bs